spring.application.name=text-processing-engine

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Keep embedded Tomcat socket open for longer data streams
server.connection-timeout=600000
